# Generated by Django 2.1.5 on 2019-01-12 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20190111_2259'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='content',
            field=models.TextField(default=1, verbose_name='作业内容'),
        ),
    ]
