# Generated by Django 2.1.5 on 2019-01-13 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_homeworkrecord_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homeworkrecord',
            name='content',
        ),
    ]
