# Generated by Django 2.1.5 on 2019-01-13 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_remove_homeworkrecord_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkrecord',
            name='content',
            field=models.TextField(default=1, verbose_name='作业内容'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='homeworkrecord',
            name='score',
            field=models.IntegerField(default=0, verbose_name='作业成绩'),
        ),
    ]
