# Generated by Django 2.1.5 on 2019-01-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_auto_20190113_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homework',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='homework',
            name='hand_in_date',
            field=models.DateTimeField(verbose_name='最晚上交时间'),
        ),
        migrations.AlterField(
            model_name='homeworkrecord',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='提交时间'),
        ),
    ]
